name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3

include:
  - board: corne_choc_pro_left
    shield: settings_reset
    snippet: studio-rpc-usb-uart
  - board: corne_choc_pro_right
    shield: settings_reset
    snippet: studio-rpc-usb-uart
